# Generated by Django 3.2.20 on 2023-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradedate', models.DateField(verbose_name='取引日')),
                ('marketcode', models.CharField(max_length=5, verbose_name='証券コード')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='取引値')),
                ('downvalue', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='前日比(値)')),
                ('downrate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='前日比(率)')),
                ('turnover', models.IntegerField(verbose_name='出来高')),
            ],
            options={
                'db_table': 'downrank',
            },
        ),
    ]
